version: '3.8'

services:
  speedtest-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Backend API
      - "5000:5000"  # Frontend
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/status"]
      interval: 30s
      timeout: 10s
      retries: 3